/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddInvoice: typeof import('./src/components/AddInvoice.vue')['default']
    AddNewAppointment: typeof import('./src/components/AddNewAppointment.vue')['default']
    AddNewCompany: typeof import('./src/components/AddNewCompany.vue')['default']
    AddNewReport: typeof import('./src/components/AddNewReport.vue')['default']
    AddNewService: typeof import('./src/components/AddNewService.vue')['default']
    AddNewStaff: typeof import('./src/components/AddNewStaff.vue')['default']
    AddNewVisit: typeof import('./src/components/AddNewVisit.vue')['default']
    AddPatient: typeof import('./src/components/AddPatient.vue')['default']
    AutoComplete: typeof import('primevue/autocomplete')['default']
    Button: typeof import('primevue/button')['default']
    Calendar: typeof import('primevue/calendar')['default']
    Chart: typeof import('primevue/chart')['default']
    Column: typeof import('primevue/column')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DeleteDialog: typeof import('./src/components/DeleteDialog.vue')['default']
    Divider: typeof import('primevue/divider')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HeroSwiper: typeof import('./src/components/HeroSwiper.vue')['default']
    IconField: typeof import('primevue/iconfield')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LoginComponent: typeof import('./src/components/LoginComponent.vue')['default']
    Logout: typeof import('./src/components/Logout.vue')['default']
    RecordsChart: typeof import('./src/components/Charts/RecordsChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    SpeedDial: typeof import('primevue/speeddial')['default']
    Textarea: typeof import('primevue/textarea')['default']
    TopBar: typeof import('./src/components/TopBar.vue')['default']
    UpdateAppointment: typeof import('./src/components/UpdateAppointment.vue')['default']
    UpdateCompany: typeof import('./src/components/UpdateCompany.vue')['default']
    UpdatePatient: typeof import('./src/components/UpdatePatient.vue')['default']
    UpdateService: typeof import('./src/components/UpdateService.vue')['default']
    UpdateStaff: typeof import('./src/components/UpdateStaff.vue')['default']
    UpdateVisit: typeof import('./src/components/UpdateVisit.vue')['default']
    ViewInvoice: typeof import('./src/components/ViewInvoice.vue')['default']
    ViewPatientDetails: typeof import('./src/components/ViewPatientDetails.vue')['default']
  }
}
